spring:
  application:
    name: rest-app
  zipkin:
    base-url: http://192.168.204.71:8080/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

app:
  id: ${random.uuid}