spring:
  application:
    name: rest-app

#server:
#  port: 8081

rest-server:
  ribbon:
    eureka:
      enabled: true
    serviceListRefreshInterval: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

app:
  id: ${random.uuid}